export default {
  SHOWDRAWER: 'SHOWDRAWER',
  HIDEDRAWER: 'HIDEDRAWER',
  CHANGECATA: 'CHANGECATA',
  GET_TOPIC_LIST: 'GET_TOPIC_LIST',
  APPEND_TOPIC_LIST: 'APPEND_TOPIC_LIST',
  GET_TOPIC_INFO: 'GET_TOPIC_INFO'
}